# Generated by Django 4.1 on 2022-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountType',
        ),
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='My_discount_code', editable=False, max_length=32),
        ),
    ]
