# Generated by Django 4.1 on 2022-08-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_discount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='type',
            field=models.CharField(default=1, max_length=16),
        ),
    ]
