# Generated by Django 4.1 on 2022-08-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('1', '%'), ('2', 'euro')], default=1, max_length=16),
        ),
    ]
