# Generated by Django 4.1 on 2022-08-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_discount_code_alter_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
