# Generated by Django 4.1 on 2022-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0009_alter_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('1', '%'), ('2', '€')], default=1, max_length=16),
        ),
    ]
