# Generated by Django 4.1 on 2022-08-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_alter_discount_code_alter_discount_type'),
        ('checkout', '0004_order_discount_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_total',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discount'),
        ),
    ]
