# Generated by Django 4.1 on 2022-08-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_discount_total_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_cart',
        ),
    ]
